apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: game-service

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: game-service
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: microservice-app
    includeSelectors: true
