apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: frontend

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - nginx-configmap.yaml
  - route.yaml

labels:
  - pairs:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: microservice-app
    includeSelectors: true
